/**
 * @file Bucket.hpp
 * @brief Intrusive FIFO bucket implementation.
 *
 * Generated by Eliot.
 *
 * This file implements a lightweight intrusive queue.
 *
 * Items stored in the bucket must contain a `next` pointer.
 *
 * This file was automatically generated.
 */

#ifndef ELIOT_BUCKET_H
#define ELIOT_BUCKET_H

#include <cstdint>
#include <concepts>

namespace eliot::core {

/**
 * @brief Concept defining a valid bucket item.
 *
 * Item must contain a member pointer `next`
 * convertible to T*.
 */
template<typename T>
concept BucketItem = requires(T* item) {
    { item->next } -> std::convertible_to<T*>;
};

/**
 * @brief Intrusive FIFO queue.
 *
 * Does not allocate memory. Instead, stored items
 * contain their own linkage pointer (`next`).
 *
 * @tparam Item Type satisfying BucketItem concept.
 */
template<BucketItem Item>
class Bucket {
public:
    /**
     * @brief Inserts item at the end of the bucket.
     *
     * @param item Pointer to item.
     */
    inline void push(Item* item) noexcept {
        item->next = nullptr;
        if (_tail) {
            _tail->next = item;
        } else {
            _head = item;
        }
        _tail = item;
    }

    /**
     * @brief Removes and returns first item.
     *
     * @return Pointer to item or nullptr if empty.
     */
    inline Item* pop() noexcept {
        if (!_head) 
            return nullptr;
        Item* item = _head;
        _head = _head->next;
        if (!_head) 
            _tail = nullptr;
        return item;
    }
    
private:
    ///> Pointer to first item.
    Item* _head = nullptr;

    ///> Pointer to last item.
    Item* _tail = nullptr;
};

}   // namespace eliot::core

#endif
