set(ELIOT_GENERATED_DIR "${CMAKE_CURRENT_SOURCE_DIR}/..")

file(GLOB_RECURSE ELIOT_GENERATED_SOURCES
    CONFIGURE_DEPENDS
    "${ELIOT_GENERATED_DIR}/*.cpp"
)

list(REMOVE_ITEM ELIOT_GENERATED_SOURCES
    "${ELIOT_GENERATED_DIR}/eliot.cpp"
)

add_library(eliot_generated STATIC
    ${ELIOT_GENERATED_SOURCES}
)

target_include_directories(eliot_generated
    PUBLIC
        ${CMAKE_CURRENT_SOURCE_DIR}
)
