/**
 * @file Time.hpp
 * @brief Lightweight time provider.
 *
 * Generated by Eliot.
 *
 * This file provides a cached monotonic time source.
 *
 * Time is read once per processing iteration and cached to
 * avoid repeated system calls.
 *
 * This file was automatically generated.
 */

#ifndef ELIOT_TIME_H
#define ELIOT_TIME_H

#include <stdint.h>

#ifndef __APPLE__
#include <time.h>
#else
#include <mach/mach_time.h>
#endif

namespace eliot_generated {

    /**
     * @brief Cached time utility.
     *
     * Provides millisecond-resolution monotonic time.
     * The value is cached per iteration and refreshed
     * explicitly using reset().
     */
    struct Time {

        /**
         * @brief Returns current monotonic time in milliseconds.
         *
         * Time is read from the system clock only once per
         * iteration and cached for subsequent calls.
         */
        static inline uint64_t now() noexcept {
            if (!_updated) {
                _global_time = _read_clock_ms();
                _updated = true;
            }
            return _global_time;
        }

        /**
         * @brief Resets cached time value.
         *
         * Forces next call to now() to refresh system time.
         */
        static inline void reset() {
            _updated = false;
        }

        private:

            ///> Cached global monotonic time value (milliseconds).
            inline static uint64_t _global_time = 0;

            ///> Indicates whether cached value is valid.
            inline static bool _updated = false;

            /**
             * @brief Reads monotonic clock in milliseconds.
             *
             * Uses platform-specific clock:
             *  - Linux: CLOCK_MONOTONIC_COARSE
             *  - macOS: mach_absolute_time()
             */
            static inline uint64_t _read_clock_ms() {
#ifndef __APPLE__
                // Fixed-point scaling factor for ns to ms conversion
                static constexpr uint64_t factor = (1ull << 32) / 1000000ull;

                struct timespec ts;
                clock_gettime(CLOCK_MONOTONIC_COARSE, &ts);

                uint64_t ns = (uint64_t)ts.tv_sec * 1000000000ull + ts.tv_nsec;
                return (ns * factor) >> 32;
#else
                static mach_timebase_info_data_t tb = {0};
                if (tb.denom == 0) mach_timebase_info(&tb);

                uint64_t t = mach_absolute_time();
                uint64_t ns = (t * tb.numer) / tb.denom;
                return ns / 1000000ull;
#endif
            }
    };
}

#endif
