/**
 * @file xoroshiro128plus.hpp
 * @brief xoroshiro128+ pseudo-random number generator implementation.
 *
 * Generated by Eliot.
 *
 * This file implements a fast 64-bit pseudo-random number generator
 * based on the xoroshiro128+ algorithm. It is used internally for
 * pseudo-random value generation in actions and conditions.
 * Algorithm source: https://xorshift.di.unimi.it/xoroshiro128plus.c
 *
 * The generator is seeded using splitmix64 to ensure proper state
 * initialization.
 *
 * This file was automatically generated.
 */

#ifndef ELIOT_XOROSHIRO128PLUS_H
#define ELIOT_XOROSHIRO128PLUS_H

#include <stdint.h>

namespace eliot_generated {

    /**
     * @brief xoroshiro128+ random number generator.
     *
     * Provides fast 64-bit pseudo-random number generation.
     */
    struct xoroshiro128plus {

        ///> Internal state part 0.
        uint64_t s0;

        ///> Internal state part 1.
        uint64_t s1;

        /**
         * @brief 64-bit left rotation.
         */
        static inline uint64_t rotl(uint64_t x, int k) noexcept {
            return (x << k) | (x >> (64 - k));
        }

        /**
         * @brief Constructs generator with given seed.
         *
         * State is initialized using splitmix64.
         *
         * @param seed Initial seed value.
         */
        explicit xoroshiro128plus(uint64_t seed) noexcept {
            uint64_t x = seed;
            s0 = _splitmix64(x);
            s1 = _splitmix64(x);

            // Prevent all-zero state
            if (s0 == 0 && s1 == 0)
                s1 = 1;
        }

        /**
         * @brief Generates next 64-bit pseudo-random value.
         */
        inline uint64_t next() noexcept {
            uint64_t result = s0 + s1;

            s1 ^= s0;
            s0 = rotl(s0, 24) ^ s1 ^ (s1 << 16);
            s1 = rotl(s1, 37);

            return result;
        }

        /**
         * @brief Generates uniform value in range [0, n).
         *
         * @param n Upper bound (exclusive).
         */
        inline uint64_t next_range(uint64_t n) noexcept {
            return (uint64_t)(((__uint128_t)next() * n) >> 64);
        }

        private:

            /**
             * @brief splitmix64 state expansion function.
             *
             * Used for seed scrambling and state initialization.
             */
            static inline uint64_t _splitmix64(uint64_t& x) noexcept {
                x += 0x9E3779B97F4A7C15ULL;
                uint64_t z = x;
                z = (z ^ (z >> 30)) * 0xBF58476D1CE4E5B9ULL;
                z = (z ^ (z >> 27)) * 0x94D049BB133111EBULL;
                return z ^ (z >> 31);
            }
    };
}

#endif
