/**
 * @file Condition.hpp
 * @brief Condition interface definition.
 *
 * Generated by Eliot.
 *
 * This file defines the concept required for conditions
 * used inside decision nodes the generated fault model.
 *
 * Conditions evaluate packet state and return a boolean result
 * determining the next transition in the fault model.
 *
 * This file was automatically generated.
 */

#ifndef ELIOT_CONDITION_H
#define ELIOT_CONDITION_H

#include <concepts>

namespace eliot::core {

/**
 * @brief Concept defining a valid condition.
 *
 * A condition must provide:
 *  - bool fulfilled(const Packet*)
 *
 * either as a member function or as a static function.
 */
template<typename T, typename Packet>
concept ConditionConcept = 
    requires(T condition, const Packet* packet) {
        { condition.fulfilled(packet) } -> std::convertible_to<bool>;
    } || 
    requires(const Packet* packet) {
        { T::fulfilled(packet) } -> std::convertible_to<bool>;
    };

/**
 * @brief Evaluates instance-based condition.
 *
 * @tparam C Condition type.
 * @tparam Packet Packet type.
 * @param condition Condition instance.
 * @param packet Pointer to packet.
 *
 * @return True if condition is satisfied.
 */
template<typename C, typename Packet>
requires ConditionConcept<C, Packet>
inline bool evaluate_condition(C& condition, const Packet* packet) noexcept {
    return condition.fulfilled(packet);
}

/**
 * @brief Evaluates static condition.
 *
 * @tparam C Condition type.
 * @tparam Packet Packet type.
 * @param packet Pointer to packet.
 *
 * @return True if condition is satisfied.
 */
template<typename C, typename Packet>
requires ConditionConcept<C, Packet>
inline bool evaluate_condition(const Packet* packet) noexcept {
    return C::fulfilled(packet);
}

}   // namespace eliot::core

#endif
