/**
 * @file State.hpp
 * @brief State node interface definition.
 *
 * Generated by Eliot.
 *
 * This file defines the concept required for state nodes
 * used inside the generated fault model.
 *
 * A state node determines the next state of a packet.
 *
 * This file was automatically generated.
 */

#ifndef ELIOT_STATE_H
#define ELIOT_STATE_H

#include <concepts>

namespace eliot_generated {

    /**
     * @brief Concept defining a valid state node.
     *
     * State node must provide method:
     *  - get_next_packet_state()
     *
     * returning next packet state identifier.
     */
    template<typename T>
    concept StateConcept = 
        requires(T state) {
            { state.get_next_packet_state() } -> std::convertible_to<unsigned>;
        };

    /**
     * @brief Retrieves next packet state from state node.
     *
     * Provides uniform dispatch for all generated
     * state node implementations.
     *
     * @tparam G Type satisfying StateConcept.
     * @param state Reference to state node.
     *
     * @return Next packet state identifier.
     */
    template<StateConcept G>
    inline unsigned get_next_state(G& state) noexcept {
        return state.get_next_packet_state();
    }
}

#endif
