/**
 * @file Calendar.hpp
 * @brief Hierarchical timer wheel scheduler.
 *
 * Generated by Eliot.
 *
 * This file implements a multi-level timer wheel used for
 * efficient packet scheduling.
 *
 * The scheduler provides near O(1) insertion and retrieval
 * for delayed packets.
 *
 * This file was automatically generated.
 */

#ifndef ELIOT_CALENDAR_H
#define ELIOT_CALENDAR_H

#include <vector>
#include <optional>
#include <array>
#include "../Time.hpp"
#include "../Bucket.hpp"
#include "../ItemPool.hpp"
#include "../../Packet.hpp"

namespace eliot::core {

    /**
     * @brief Multi-level timer wheel scheduler.
     *
     * Implements a three-level hierarchical timer wheel
     * for efficient delay-based packet scheduling.
     */
    struct Calendar {

        /**
         * @brief Schedules packet for future execution.
         *
         * @param packet Packet to schedule.
         * @param delay Delay in milliseconds.
         */
        void schedule(generated::Packet* packet, uint64_t delay) noexcept;

        /**
         * @brief Returns next ready packet if available.
         *
         * @return Pointer to ready packet or nullptr.
         */
        generated::Packet* get_ready() noexcept;

        /**
         * @brief Returns true if no packets are scheduled.
         */
        inline bool empty() const noexcept { return _size == 0; }

        /**
         * @brief Destroys calendar and clears all scheduled packets.
         */
        ~Calendar() noexcept;

        private:

            ///> Number of slots per wheel level.
            static constexpr uint32_t _SLOTS = 256;

            ///> Bit mask for slot indexing.
            static constexpr uint64_t _MASK = _SLOTS - 1;

            ///> Time span of first level.
            static constexpr uint64_t _L0_SPAN = _SLOTS;

            ///> Time span of second level.
            static constexpr uint64_t _L1_SPAN = _SLOTS * _SLOTS;

            ///> Time span of third level.
            static constexpr uint64_t _L2_SPAN = _L1_SPAN * _SLOTS;

            ///> Number of scheduled items.
            size_t _size = 0;

            ///> Start reference time.
            uint64_t _start = Time::now();

            ///> Current scheduler tick.
            uint64_t _current_tick = 0;
        
            /**
             * @brief Internal calendar item.
             *
             * Represents one scheduled packet.
             */
            struct CalendarItem {
                CalendarItem(uint64_t t, generated::Packet *p) noexcept 
                    : tick(t), packet(p), next(nullptr) {}

                ///> Scheduled tick.
                uint64_t tick;

                ///> Associated packet.
                generated::Packet* packet;

                ///> Intrusive linked list pointer.
                CalendarItem* next = nullptr;

                // Disable dynamic allocation
                static void* operator new(std::size_t) = delete;
                static void operator delete(void*) = delete;
                static void* operator new[](std::size_t) = delete;
                static void  operator delete[](void*) = delete;
            };

            ///> Bucket type used for each wheel slot.
            using BucketT = Bucket<CalendarItem>;

            ///> First-level timer wheel.
            std::array<BucketT, _SLOTS> _wheel0{};

            ///> Second-level timer wheel.
            std::array<BucketT, _SLOTS> _wheel1{};

            ///> Third-level timer wheel.
            std::array<BucketT, _SLOTS> _wheel2{};

            ///> Item pool for calendar items.
            ItemPool<CalendarItem, 4096> _item_pool;

            /**
             * @brief Cascades items from level 1 to level 0.
             */
            void _cascade_from_L1() noexcept;

            /**
             * @brief Cascades items from level 2 to level 1.
             */
            void _cascade_from_L2() noexcept;

            /**
             * @brief Clears all items from specified wheel.
             */
            void _clear_wheel(std::array<BucketT, _SLOTS>& wheel) noexcept;
            
            /**
             * @brief Returns current tick based on monotonic clock.
             *
             * Converts monotonic time to scheduler-relative tick.
             */
            inline uint64_t _current_tick_from_clock() const noexcept {
                uint64_t now = Time::now();
                return now < _start ? _current_tick : now - _start;
            }
    };
}

#endif
