/**
 * @file eliot.cpp
 * @brief Entry point of the generated code.
 *
 * Generated by Eliot.
 *
 * This file initializes the packet processing runtime,
 * installs signal handlers and starts the processing loop.
 * 
 * This file was automatically generated.
 */

#include "PacketProcessor.hpp"
#include <csignal>

/**
 * @brief Application entry point.
 *
 * Initializes the packet processor with command line arguments
 * and starts the main processing loop.
 *
 * A SIGINT (Ctrl+C) handler is registered to gracefully stop
 * the packet processor.
 *
 * @param argc Number of command line arguments.
 * @param argv Array of command line argument strings.
 *
 * @return EXIT_SUCCESS on normal termination,
 *         EXIT_FAILURE if a runtime error occurs.
 */
int main(int argc, char **argv) {
    // Register SIGINT handler for graceful shutdown
    std::signal(SIGINT, [](int){
        eliot::generated::PacketProcessor<eliot::backend::ActiveTraits>::stop();
    });

    try {
        // Create packet processor
        eliot::generated::PacketProcessor<eliot::backend::ActiveTraits> processor(argc, argv);

        // Start processing loop
        processor.run();
        return EXIT_SUCCESS;
    }
    catch (const std::runtime_error& e) {
        std::cerr << "ERROR: " << e.what() << std::endl;
        return EXIT_FAILURE;
    }
}
